### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dataf3l** [vefstathiou/SO_word2vec#3]
What was the motivation for creating this model?
What are its applications?
I'm honestly curious!

**Comment by vefstathiou** [comment]
Thanks for your interest! The preprint of the accompanying paper gives some motivation and lists a couple of downstream tasks where such a model could be used.

**Comment by dataf3l** [comment]
Do you have a link?

**Comment by vefstathiou** [comment]
Here: https://github.com/vefstathiou/SO_word2vec/blob/master/MSR18-w2v.pdf
